관통 프로젝트/pjt06/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('<int:user_pk>/', views.profile, name='profile'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/follow', views.follow, name='follow'),
]

관통 프로젝트/pjt06/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),  
    path('<int:board_pk>/likes/', views.likes, name='likes'), 
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

관통 프로젝트/pjt06/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),

]

관통 프로젝트/pjt06/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>
        </li>
        <li>
          {% if request.user.is_authenticated %}
            <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' request.user.id %}">프로필 페이지</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

관통 프로젝트/pjt06/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>Document</title>
  <style >
    form {
      display: inline;
      margin-left: 6px;
    }

  </style>
</head>
<body>
  <div class="mt-3 container">
    
    <div class="row d-flex justify-content-between">
      <div class='col-6'>
        {% if request.user.is_authenticated %}
        <h3>Hello, {{ user.username }}</h3>
        {% else %}
        <h3>로그인을 해주세요</h3>
        {% endif %}
      </div>
      <div class="col-6 d-flex justify-content-end">
        {% if request.user.is_authenticated %}
        <a id='edit_profile' class="btn btn-light" href="{% url "accounts:update" %}">회원정보수정</a>
        <form action="{% url "accounts:logout" %}" method="POST">
          {% csrf_token %}
          <input class='btn btn-light' type="submit" value="LOGOUT">
        </form>
        {% else %}
          <a class="btn btn-light" href="{% url "accounts:login" %}">LOGIN</a>
          <a class="btn btn-light" href="{% url "accounts:signup" %}">SIGNUP</a>
        {% endif %}
      </div>
    <div>
  <hr>
    <div class="mt-3 mb-4">
      {% include '_navbar.html' %}
    </div>
    <div class="mb-5">
      
  {% block content %}
  {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>