관통 프로젝트/pjt06/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('<int:user_pk>/', views.profile, name='profile'),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/follow', views.follow, name='follow'),
]

관통 프로젝트/pjt06/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),  
    path('<int:board_pk>/likes/', views.likes, name='likes'), 
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

관통 프로젝트/pjt06/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),

]

관통 프로젝트/pjt06/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

관통 프로젝트/pjt06/boards/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 조회수는 상세 페이지에서만 조회 가능하다고 가정
    views = models.IntegerField(default=0)
    # author 추가
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=0)
    # like_users 추가
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_board'
    )

class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # author 추가
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=0)

관통 프로젝트/pjt06/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model() 
        fields = ['email', 'last_name', 'first_name',]

관통 프로젝트/pjt06/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserCreationForm, CustomUserChangeForm


def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('accounts:login')
    return redirect('boards:index')


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


@login_required
def edit(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = CustomUserChangeForm(instance=request.user)
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/edit.html', context)


@login_required
def password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = PasswordChangeForm(request.user)
    
    context = {
        'form': form,
    }
    return render(request, 'accounts/password.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('boards:index')


@login_required
def resign(request):
    if request.method == 'POST':
        request.user.delete()
        auth_logout(request)
        return redirect('accounts:login')
    return redirect('accounts:profile')


def profile(request, user_pk):
    # User의 Detail 페이지
    # User를 조회
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('boards:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user
    
    if me != you:
        # 내가 상대방의 팔로워 목록에 있다면
        if me in you.followers.all():
            # 팔로우 취소
            you.followers.remove(me)
            # me.followings.remove(you)
        else:
            you.followers.add(me)
            # me.followings.add(you)
    return redirect('accounts:profile', you.id)

관통 프로젝트/pjt06/accounts/templates/accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>비밀번호 변경</h1>
  <form action="{% url 'change_password' user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

관통 프로젝트/pjt06/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인</h1>
  <form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>

</body>
</html>

관통 프로젝트/pjt06/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
  <h1 class='col-8'>{{ person.username }}님의 프로필 페이지</h1>
  <div class='col-4 d-flex justify-content-end'>
    <p>팔로잉 : {{ person.followings.all|length }} / 팔로워 : {{ person.followers.all|length }}</p>
    {% if request.user.is_authenticated %}
      {% if request.user != person %}
          <form action="{% url "accounts:follow" person.pk %}" method="POST">
            {% csrf_token %}
            {% if request.user in person.followers.all %}
              <input class="btn btn-light"type="submit" value="Unfollow">
            {% else %}
              <input class="btn btn-light" type="submit" value="Follow">
            {% endif %}
          </form>
      {% endif %}
    {% endif %}
  </div>
</div>


<div>
  <p>회원번호 : {{ person.pk }}</p>
  <p>유저이름: {{ person.username }}</p>
  <p>가입날짜 : {{ person.date_joined }}</p>
</div>


<hr>

<div>
  <h2>유저가 쓴 글</h2>
  {% for board in person.board_set.all %}
    <div class="bg-light">
      <p>글번호 : {{ board.id }}</p>
      <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
    </div>
  {% endfor %}
</div>

<hr>

<div>
  <h2>유저가 쓴 댓글</h2>
  {% if person.comment_set.all|length == 0 %} 아직 작성한 댓글이 없습니다.
  {% else %}
    {% for comment in person.comment_set.all %}
        {{ comment.content }}
    {% endfor %}
  {% endif %}
</div>

<hr>

<div>
  <h2>팔로워</h2>
  {% if person.followers.all|length == 0 %} 팔로워한 사람이 없습니다.
  {% else %}
    {% for person in person.followers.all %}
      <p>{{ person.username }}</p>
    {% endfor %}
  {% endif %}
</div>

{% comment %}

<h2>좋아요를 누른 게시글</h2>
{% for board in person.like_articles.all %}
  <p>{{ article.title }}</p>
{% endfor %}

{% endcomment %}



{% endblock content %}

관통 프로젝트/pjt06/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

관통 프로젝트/pjt06/accounts/templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원정보수정</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>